Recommendation.create!([
  {modality: "Swedish", duration: "60 minutes", frequency: "bi-monthly", description: "Smooth, relaxing technique designed to promote blood flow, reduce stress and improve health. This is the most commom type of massage in the U.S.", pressure: "light"},
  {modality: "Deep Tissue", duration: "60 minutes", frequency: "bi-monthly", description: " A technique using deeper pressure to release chronic muscle tension and reduce  muscular adhesions.", pressure: "deep"},
  {modality: "Neuromuscular", duration: "90 minutes", frequency: "weekly", description: "A specialized form of deep tissue therapy that uses static pressure on trigger points in order to relieve muscular pain.", pressure: "deep"},
  {modality: "Reiki", duration: "60 minutes", frequency: "bi-monthly", description: "A Japanese technique for stress reduction and relaxation.", pressure: "light"},
  {modality: "Myofascial Release", duration: "90 minutes", frequency: "monthly", description: "The application of gentle, sustained pressure on connective tissue in order to relieve myofascial restrictions, which results in better range of motion and pain relief.", pressure: "light"},
  {modality: "Indian Head Massage", duration: "60 minutes", frequency: "quarterly", description: "A form of massage, originating from Ayurveda, that focuses on the face, head, neck and shoulders. It is very relaxing and has a balancing effect, often resulting in a reduction in stress and tension.", pressure: "light"},
  {modality: "Craniosacral Therapy", duration: "60 minutes", frequency: "monthly", description: "A gentle approach that helps release tensions deep in the body by promoting flow of the craniosacral fluid surrounding the spine and cranium.", pressure: "light"},
  {modality: "Lymphatic Drainage", duration: "90 minutes", frequency: "monthly", description: "A type of gentle massage which is intended to increase the natural drainage of lymph nodes, thereby carrying waste products away from the tissues. It also increases the production of lymphocytes which improves the body's ability to fight infection. ", pressure: "light"},
  {modality: "Foot and Hand Reflexology", duration: "90 minutes", frequency: "monthly", description: "Application of pressure to certain points on the hands or feet that benefit organs and health.", pressure: "medium"},
  {modality: "Accupresure Massage", duration: "30 minutes", frequency: "weekly", description: "Based on traditional Chinese medicine, accurpresure massage focuses on points that lie along meridians, or channels, in your body. When pressure is applied to these points, energy blockages are removed, resulting in pain relief and improved general health.", pressure: "medium"},
  {modality: "Pregnancy Massage", duration: "60 minutes", frequency: "monthly", description: "A specialized massage for expectant Mothers designed to relieve back pain and other discomforts associated with pregnancy. Not recommended during first trimester.", pressure: "light"}
])
Symptom.create!([
  {name: "Neck Pain", severity: 5, recommendation_id: 1},
  {name: "Neck and Shoulder Tension", severity: 7, recommendation_id: 1},
  {name: "Lower Back Pain(due to pregnancy)", severity: 5, recommendation_id: 11},
  {name: "Upper Back Pain(due to pregnancy)", severity: 5, recommendation_id: 11},
  {name: "Upper Back Pain", severity: 10, recommendation_id: 2},
  {name: "Shoulder Pain", severity: 10, recommendation_id: 2},
  {name: "General Muscular Pain", severity: 10, recommendation_id: 3},
  {name: "Depression", severity: 5, recommendation_id: 4},
  {name: "Migraine Headaches", severity: 10, recommendation_id: 4},
  {name: "Frozen Shoulder", severity: 5, recommendation_id: 5},
  {name: "Whiplash", severity: 5, recommendation_id: 5},
  {name: "Mental Fatigue", severity: 5, recommendation_id: 6},
  {name: "Tension Headaches", severity: 5, recommendation_id: 6},
  {name: "TMJ", severity: 10, recommendation_id: 7},
  {name: "Chronic Neck and Back Pain", severity: 10, recommendation_id: 7},
  {name: "Chronic Fatigue Syndrome", severity: 10, recommendation_id: 8},
  {name: "Chronic Sinusitis", severity: 10, recommendation_id: 8},
  {name: "Digestive Disorders", severity: 10, recommendation_id: 9},
  {name: "Insomnia", severity: 10, recommendation_id: 9},
  {name: "Acute Pain", severity: 10, recommendation_id: 10},
  {name: "Insomnia", severity: 10, recommendation_id: 10}
])
